## Table of Content
1. **[Concatenate](#Concatenate)**
2. **[Merging and Joining](#Merging)**
3. **[Reshaping](#Reshaping)**
4. **[Pivot Table](#Pivote)**
5. **[Cross Table](#crosst)**
6. **[Duplicate](#Duplicate)**
7. **[Dropping Rows and Columns](#drop)**
8. **[Map and Replace](#Map)**
9. **[Groupby in Pandas](#Groupby)**
10. **[Summary Statistics](#Summary_Statistics)**

<a id="Concatenate"> </a>
### 1. Concatenate

Concatenation is a process of joining objects along a particular axis, with set logic applied along the other axes, if any (a series does not have any other axes)<br>
                   The main parameters involved in pandas concatenation are - object, axis, handling of other axes, and keys.

**Concatenate pandas Series**

In [2]:
# import the library pandas as pd
import pandas as pd

# import the library NumPy as np
import numpy as np

In [3]:
# create a series from list
sales_a = pd.Series([101,102,103,104,105,106])

# create another series from list
sales_b = pd.Series([107,108,109,110,111,112])

In [ ]:
# concatenate the pandas series
pd.concat([sales_a,sales_b])

0    101
1    102
2    103
3    104
4    105
5    106
0    107
1    108
2    109
3    110
4    111
5    112
dtype: int64

**Add a hierarchical index to a pandas Series**

In [ ]:
# concatenate the series 
# keys adds hierarchical indexes
pd.concat([sales_a,sales_b], keys = ['a', 'b'])

a  0    101
   1    102
   2    103
   3    104
   4    105
   5    106
b  0    107
   1    108
   2    109
   3    110
   4    111
   5    112
dtype: int64

**Label the index**

In [ ]:
# 'names' parameter assigns labels to 'keys' and 'indexes'
pd.concat([sales_a, sales_b], keys=['a', 'b'], names=['Series', 'Row ID'])

Series  Row ID
a       0         101
        1         102
        2         103
        3         104
        4         105
        5         106
b       0         107
        1         108
        2         109
        3         110
        4         111
        5         112
dtype: int64

**Concatenating DataFrames**

To concatenate DataFrames, let us first create three DataFrame
1. df_prof_info_A: professional information on employees of company A
2. df_prof_info_B: professional information on employees of company B
3. df_pers_info_A: personal information on employees of company A


In [3]:
# create a DataFrame from a dictionary
df_prof_info_A = pd.DataFrame({
   'Emp_ID': [1001,1002,1003,1004,1005],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Stephan'],
   'Gender':['M', 'F', 'M', 'F', 'M'],
   'Company':['Apple','Walmart','Intel','Cummins','Ford'],
   'Salary':[67000,90000,87000,69000,78000]},
   index=[101,102,103,104,105])

# print the DataFrame
print("The first DataFrame is : \n",df_prof_info_A)

print("\n\n")

# create a DataFrame from a dictionary
df_prof_info_B = pd.DataFrame({
    'Emp_ID': [1006,1007,1008,1009,1010,1011],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty','James'],
    'Gender':['M', 'M', 'M', 'F', 'F','M'],
   'Company':['Cognizant','Apple','Intel','Cummins','Walmart','Intel'],
   'Salary':[89000,80000,79000,97000,88000,89000]},
   index=[106,107,108,109,110,111])

# print the DataFrame
print("The second DataFrame is : \n",df_prof_info_B)

print("\n\n")

# create a DataFrame from a dictionary
df_pers_info_A = pd.DataFrame({
     'Emp_ID': [1001,1002,1003,1004,1005],
   'Hometown': ['New York', 'London', 'San Francisco', 'Seattle', 'Madrid'],
     'Gender':['M', 'F', 'M', 'F', 'M'],
    'Marital':['Married','Divorsed','Single','Married','Single'],
   'Dependents':[1,1,3,2,1]},
   index=[101,102,103,104,105])

# print the DataFrame
print("The third DataFrame is : \n",df_pers_info_A)

print("\n\n")

# create a DataFrame from a dictionary
df_pers_info_B = pd.DataFrame({
     'Emp_ID': [1006,1007,1009,1010,1011,1012],
   'Hometown': ['Paris', 'Boston', 'San Francisco', 'Seattle', 'London','London'],
    'Marital':['Married','Divorsed','Single','Married','Single','Single'],
   'Dependents':[1,1,3,2,1,2]},
   index=[101,102,103,104,105,106])

# print the DataFrame
print("The fourth DataFrame is : \n",df_pers_info_B)

The first DataFrame is : 
      Emp_ID     Name Gender  Company  Salary
101    1001     Alex      M    Apple   67000
102    1002      Amy      F  Walmart   90000
103    1003    Allen      M    Intel   87000
104    1004    Alice      F  Cummins   69000
105    1005  Stephan      M     Ford   78000



The second DataFrame is : 
      Emp_ID   Name Gender    Company  Salary
106    1006  Billy      M  Cognizant   89000
107    1007  Brian      M      Apple   80000
108    1008   Bran      M      Intel   79000
109    1009  Bryce      F    Cummins   97000
110    1010  Betty      F    Walmart   88000
111    1011  James      M      Intel   89000



The third DataFrame is : 
      Emp_ID       Hometown Gender   Marital  Dependents
101    1001       New York      M   Married           1
102    1002         London      F  Divorsed           1
103    1003  San Francisco      M    Single           3
104    1004        Seattle      F   Married           2
105    1005         Madrid      M    Single    

**Concatenating pandas DataFrames using `.concat()`**

**Combine DataFrames vertically**

In [4]:
# concatenate the data frame
print(pd.concat([df_prof_info_A,df_prof_info_B]))

     Emp_ID     Name Gender    Company  Salary
101    1001     Alex      M      Apple   67000
102    1002      Amy      F    Walmart   90000
103    1003    Allen      M      Intel   87000
104    1004    Alice      F    Cummins   69000
105    1005  Stephan      M       Ford   78000
106    1006    Billy      M  Cognizant   89000
107    1007    Brian      M      Apple   80000
108    1008     Bran      M      Intel   79000
109    1009    Bryce      F    Cummins   97000
110    1010    Betty      F    Walmart   88000
111    1011    James      M      Intel   89000


**Combine DataFrames horizontally**

In [9]:
# combine Pandas Dataframes horizontally
# axis specifies the axis to concatenate along, here 1 indicates columns
pd.concat([df_prof_info_A, df_pers_info_A], axis=1)

Emp_ID     Name Gender  Company  Salary  Emp_ID       Hometown Gender  \
101    1001     Alex      M    Apple   67000    1001       New York      M   
102    1002      Amy      F  Walmart   90000    1002         London      F   
103    1003    Allen      M    Intel   87000    1003  San Francisco      M   
104    1004    Alice      F  Cummins   69000    1004        Seattle      F   
105    1005  Stephan      M     Ford   78000    1005         Madrid      M   

      Marital  Dependents  
101   Married           1  
102  Divorsed           1  
103    Single           3  
104   Married           2  
105    Single           1

Combining DataFrames horizontally with duplicate columns removed.

In [6]:
# combine DataFrame with duplicate columns removed
# T: transposes the DataFrame
# drop_duplicates(): drops the duplicate rows in a DataFrame
pd.concat([df_prof_info_A, df_pers_info_A], axis=1).T.drop_duplicates().T

Emp_ID     Name Gender  Company Salary       Hometown   Marital Dependents
101   1001     Alex      M    Apple  67000       New York   Married          1
102   1002      Amy      F  Walmart  90000         London  Divorsed          1
103   1003    Allen      M    Intel  87000  San Francisco    Single          3
104   1004    Alice      F  Cummins  69000        Seattle   Married          2
105   1005  Stephan      M     Ford  78000         Madrid    Single          1

**Concatenating data frames ignoring index values**

In [ ]:
# concatenate DataFrames
# ignore_index if True, assigns index values begining with zero
pd.concat([df_prof_info_A, df_prof_info_B], ignore_index=True)

Emp_ID     Name Gender    Company  Salary
0     1001     Alex      M      Apple   67000
1     1002      Amy      F    Walmart   90000
2     1003    Allen      M      Intel   87000
3     1004    Alice      F    Cummins   69000
4     1005  Stephan      M       Ford   78000
5     1006    Billy      M  Cognizant   89000
6     1007    Brian      M      Apple   80000
7     1008     Bran      M      Intel   79000
8     1009    Bryce      F    Cummins   97000
9     1010    Betty      F    Walmart   88000
10    1011    James      M      Intel   89000

**Concatenating Pandas Dataframes using `.append()`**

In [ ]:
# append DataFrame df_company_B to df_company_A
df_prof_info_A.append(df_prof_info_B)

Emp_ID     Name Gender    Company  Salary
101    1001     Alex      M      Apple   67000
102    1002      Amy      F    Walmart   90000
103    1003    Allen      M      Intel   87000
104    1004    Alice      F    Cummins   69000
105    1005  Stephan      M       Ford   78000
106    1006    Billy      M  Cognizant   89000
107    1007    Brian      M      Apple   80000
108    1008     Bran      M      Intel   79000
109    1009    Bryce      F    Cummins   97000
110    1010    Betty      F    Walmart   88000
111    1011    James      M      Intel   89000

<a id="Merging"> </a>
### 2. Merging and Joining

Merging two datasets is a process of bringing two datasets to form one, by aligning the rows from both the datasets based on common attributes or columns

### Concatenate using `.merge()`

Concatenate the personal and professional information on employees in company A.

In [6]:
# concatenate the DataFrames 
# 'on' specifies the column(s) based on which to join the DataFrames 
# suffixes: specifies the suffix for duplicate columns
# the (' ',' ') indicates there are no suffixes given
# T: transposes the DataFrame
# drop_duplicates(): drops the duplicate rows in a DataFrame
pd.merge(df_prof_info_A, df_pers_info_A, on='Emp_ID',suffixes=(' ',' ') ).T.drop_duplicates().T

Emp_ID     Name Gender   Company Salary       Hometown   Marital Dependents
0   1001     Alex       M    Apple  67000       New York   Married          1
1   1002      Amy       F  Walmart  90000         London  Divorsed          1
2   1003    Allen       M    Intel  87000  San Francisco    Single          3
3   1004    Alice       F  Cummins  69000        Seattle   Married          2
4   1005  Stephan       M     Ford  78000         Madrid    Single          1

The rows having common employee ID's are merged to give the resultant DataFrame.

**Merging using multiple keys**

Now, let us Concatenate the personal and professional information on employees in company A. 

In [ ]:
# concatenate the DataFrames 
# 'on' specifies the column(s) based on which to join the DataFrames 
pd.merge(df_prof_info_A, df_pers_info_A, on=["Emp_ID","Gender"])

Emp_ID     Name Gender  Company  Salary       Hometown   Marital  \
0    1001     Alex      M    Apple   67000       New York   Married   
1    1002      Amy      F  Walmart   90000         London  Divorsed   
2    1003    Allen      M    Intel   87000  San Francisco    Single   
3    1004    Alice      F  Cummins   69000        Seattle   Married   
4    1005  Stephan      M     Ford   78000         Madrid    Single   

   Dependents  
0           1  
1           1  
2           3  
3           2  
4           1

The rows having common employee ID and gender are merged to give the resultant DataFrame.

**Merging on the Basis of Index**

This function helps to merge two DataFrames, based on their index.

In [ ]:
# merge the DataFrames based on their index
# 'left_index' considers index of left DataFrame to merge, here it is set to True, so it is considered
# 'right_index' considers index of right DataFrame to merge, here it is set to False, so it is not considered
# 'on' specifies the column(s) based on which to join the DataFrames 
# suffixes: specifies the suffix for duplicate columns
# the (' ',' ') indicates there are no suffixes given
# T: transposes the DataFrame
# drop_duplicates(): drops the duplicate rows in a DataFrame
pd.merge(df_prof_info_A, df_pers_info_A,  right_index = False, left_index = True, on='Emp_ID', suffixes =(' ',' ')
        ).T.drop_duplicates().T

Emp_ID     Name Gender   Company Salary       Hometown   Marital  \
101   1001     Alex       M    Apple  67000       New York   Married   
102   1002      Amy       F  Walmart  90000         London  Divorsed   
103   1003    Allen       M    Intel  87000  San Francisco    Single   
104   1004    Alice       F  Cummins  69000        Seattle   Married   
105   1005  Stephan       M     Ford  78000         Madrid    Single   

    Dependents  
101          1  
102          1  
103          3  
104          2  
105          1

Note the resultant DataFrame takes the index of the DataFrame to the left. 

**`merge()` allows you to perform natural join, left join, right join, and full outer join in pandas.**

**Understanding the Different Types of Merge:**

Left outer join: includes all the rows of your DataFrame x and only those from y that match. (how=‘left’).

Right outer join: includes all the rows of your DataFrame y and only those from x that match. (how=‘right’).

Inner join: includes those rows that are common to both the DataFrames. (how=‘inner’).

Full outer join: includes all rows from both DataFrames. (how=‘outer’).

**Inner Join:**<br>
It returns only the rows in which the left table has matching keys in the right table.

In [ ]:
# print the inner join of the DataFrames
# on specifies the column(s) based on which to join the DataFrames 
# how specifies the type of join
pd.merge(df_prof_info_B, df_pers_info_B, on='Emp_ID', how='inner')

Emp_ID   Name Gender    Company  Salary       Hometown   Marital  \
0    1006  Billy      M  Cognizant   89000          Paris   Married   
1    1007  Brian      M      Apple   80000         Boston  Divorsed   
2    1009  Bryce      F    Cummins   97000  San Francisco    Single   
3    1010  Betty      F    Walmart   88000        Seattle   Married   
4    1011  James      M      Intel   89000         London    Single   

   Dependents  
0           1  
1           1  
2           3  
3           2  
4           1

In professional info B we have employee ID's as 1006,1007,1008,1009,1010,1011 and we have personal info B for employee ID's 1006,1007,1009,1010,1011,1012. Because of the inner join, we notice that 1008 from the first DataFrame (professinal info) and 1012 from second DataFrame (personal info) are not part to the resultant outcome. In other words, inner join will include those rows that are common to both the DataFrames.

**Outer Join:**<br>
It returns all rows from both tables, joining records from the left, which has matching keys in the right table.

In [ ]:
# print the outer join of the DataFrames
# on specifies the column(s) based on which to join the DataFrames 
# how specifies the type of join
pd.merge(df_prof_info_B, df_pers_info_B, on='Emp_ID', how='outer')

Emp_ID   Name Gender    Company   Salary       Hometown   Marital  \
0    1006  Billy      M  Cognizant  89000.0          Paris   Married   
1    1007  Brian      M      Apple  80000.0         Boston  Divorsed   
2    1008   Bran      M      Intel  79000.0            NaN       NaN   
3    1009  Bryce      F    Cummins  97000.0  San Francisco    Single   
4    1010  Betty      F    Walmart  88000.0        Seattle   Married   
5    1011  James      M      Intel  89000.0         London    Single   
6    1012    NaN    NaN        NaN      NaN         London    Single   

   Dependents  
0         1.0  
1         1.0  
2         NaN  
3         3.0  
4         2.0  
5         1.0  
6         2.0

In professional info B we have employee ID's as 1006,1007,1008,1009,1010,1011 and we have personal info B for employee ID's 1006,1007,1009,1010,1011,1012. <br>The employee Id 1008 has no personal information available and the employee ID 1012 has no professional information available. <br>So, the outer join merged all the observations from both the DataFrames and all the missing values are marked with `NaN`.

**Left Outer Join:**<br>
It returns all rows from the left table and any rows with matching keys from the right table.

In [ ]:
# print the left join of the DataFrames
# on specifies the column(s) based on which to join the DataFrames 
# how specifies the type of join
pd.merge(df_prof_info_B, df_pers_info_B, on = 'Emp_ID', how ='left')

Emp_ID   Name Gender    Company  Salary       Hometown   Marital  \
0    1006  Billy      M  Cognizant   89000          Paris   Married   
1    1007  Brian      M      Apple   80000         Boston  Divorsed   
2    1008   Bran      M      Intel   79000            NaN       NaN   
3    1009  Bryce      F    Cummins   97000  San Francisco    Single   
4    1010  Betty      F    Walmart   88000        Seattle   Married   
5    1011  James      M      Intel   89000         London    Single   

   Dependents  
0         1.0  
1         1.0  
2         NaN  
3         3.0  
4         2.0  
5         1.0

We notice that employee ID 1008 is present in left DataFrame but not present in the right DataFrame.

Whereas employee ID 1012 is present in right DataFrame but not present in the left DataFrame.

Because of `how = 'left'`, it took all the observations from the left DataFrame (professional info) but it took only those observations from the right DataFrame (personal info) which are present in the left DataFrame and all the missing values are marked with `NaN`.

**Right Outer Join:**<br>
It returns all rows from the right table and any rows with matching keys from the left table.

In [ ]:
# print the right join of the DataFrames
# on specifies the column(s) based on which to join the DataFrames 
# how specifies the type of join
pd.merge(df_prof_info_B, df_pers_info_B, on='Emp_ID', how='right')

Emp_ID   Name Gender    Company   Salary       Hometown   Marital  \
0    1006  Billy      M  Cognizant  89000.0          Paris   Married   
1    1007  Brian      M      Apple  80000.0         Boston  Divorsed   
2    1009  Bryce      F    Cummins  97000.0  San Francisco    Single   
3    1010  Betty      F    Walmart  88000.0        Seattle   Married   
4    1011  James      M      Intel  89000.0         London    Single   
5    1012    NaN    NaN        NaN      NaN         London    Single   

   Dependents  
0           1  
1           1  
2           3  
3           2  
4           1  
5           2

We notice that employee ID 1012 is present in right DataFrame but not present in the left DataFrame.

Whereas employee ID 1008 is present in left DataFrame but not present in the right DataFrame.

Because of `how = 'right'`, it took all the observations from the right DataFrame (personal info) but it took only those observations from the left DataFrame (professional info) which are present in the right DataFrame and all the missing values are marked with `NaN`.

<a id="Reshaping"> </a>
### 3. Reshaping

**`.stack()` and `.unstack()` in Pandas:**<br>
 
Unstacking can be used to rearrange the series with hierarchical index in a DataFrame.

Stack is the inverse operation of unstack

### Methods of Multi-Index Creation

In [ ]:
# create the column names of the DataFrame
labels = pd.MultiIndex.from_product([['Before Course','After Course'],['Marks']])

# create the list of values 
marks = [[82,95],[78,89],[78,87],[76,89],[66,89]]

# create the DataFrame
# data is the values used to create the DataFrame
# index are the index name of the DataFrame
# columns are the column name of the DataFrame
df_marks = pd.DataFrame(data = marks, index = ['Alisa','Bobby','Cathrine','Jack','Mia'], columns = labels)

# print the DataFrame
df_marks

Before Course After Course
                 Marks        Marks
Alisa               82           95
Bobby               78           89
Cathrine            78           87
Jack                76           89
Mia                 66           89

We shall use the above the DataFrame henceforth.

Stack the DataFrame

In [ ]:
# stack the DataFrame
df_stacked = df_marks.stack()

# print the stacked DataFrame
print(df_stacked)

                After Course  Before Course
Alisa    Marks            95             82
Bobby    Marks            89             78
Cathrine Marks            87             78
Jack     Marks            89             76
Mia      Marks            89             66


Notice this creates two levels of indexes; the first level is the name of students, and the second level is 'Marks'. There are two indexes and is called a multi-index. 

We can convert back to a full table by unstacking, recreating a single index for each line of data.

In [ ]:
# unstack the DataFrame
df_unstacked = df_stacked.unstack()

# print the unstacked DataFrame
print (df_unstacked)

         After Course Before Course
                Marks         Marks
Alisa              95            82
Bobby              89            78
Cathrine           87            78
Jack               89            76
Mia                89            66


Let us introduce the parameter `level`  in `.stack()`.  The argument `level = 0`  stacks the column marks as 'after course' and 'before course'.

In [ ]:
# stack the DataFrame
df_stacked_level = df_marks.stack(level = 0)

# print the stacked DataFrame
df_stacked_level

Marks
Alisa    After Course      95
         Before Course     82
Bobby    After Course      89
         Before Course     78
Cathrine After Course      87
         Before Course     78
Jack     After Course      89
         Before Course     76
Mia      After Course      89
         Before Course     66

Now put `level = 1`.

In [ ]:
# stack the DataFrame
df_stacked_level = df_marks.stack(level = 1)

# print the stacked DataFrame
df_stacked_level

After Course  Before Course
Alisa    Marks            95             82
Bobby    Marks            89             78
Cathrine Marks            87             78
Jack     Marks            89             76
Mia      Marks            89             66

**Using `.melt()` method:**<br>
`.melt()` in pandas reshape dataframe from wide format to long format. It uses the `id_vars[‘col_names’]` to melt the dataframe by column names.

In [ ]:
# display DataFrame
df_prof_info_A

Emp_ID     Name Gender  Company  Salary
101    1001     Alex      M    Apple   67000
102    1002      Amy      F  Walmart   90000
103    1003    Allen      M    Intel   87000
104    1004    Alice      F  Cummins   69000
105    1005  Stephan      M     Ford   78000

In [9]:
# reshape the DataFrame using melt()
df_melt = df_prof_info_A.melt(id_vars =['Company'])  
print(df_melt.head(10)) 

   Company variable    value
0    Apple   Emp_ID     1001
1  Walmart   Emp_ID     1002
2    Intel   Emp_ID     1003
3  Cummins   Emp_ID     1004
4     Ford   Emp_ID     1005
5    Apple     Name     Alex
6  Walmart     Name      Amy
7    Intel     Name    Allen
8  Cummins     Name    Alice
9     Ford     Name  Stephan


In [10]:
df_melt = df_prof_info_A.melt(id_vars =['Company'],var_name='info',value_name='Numerical')    # just renaming
print(df_melt.head(10)) 

   Company    info Numerical
0    Apple  Emp_ID      1001
1  Walmart  Emp_ID      1002
2    Intel  Emp_ID      1003
3  Cummins  Emp_ID      1004
4     Ford  Emp_ID      1005
5    Apple    Name      Alex
6  Walmart    Name       Amy
7    Intel    Name     Allen
8  Cummins    Name     Alice
9     Ford    Name   Stephan


The column ‘variable’ contains all the columns except the identifiers, and ‘value’ contains the values of the corresponding column.

<a id="Pivote"> </a>
### 4. Pivot Table


The pivot_table() is used to create a new table for the given index. Pivot has three arguments - index, columns, and values.

In [ ]:
# create a dictionary
sales = {'Months': ['Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec'],
        'Sales': [22000,27000,25000,29000,35000,67000,78000,67000,56000,56000,89000,60000],
         'Seasons': ['Winter','Winter','Spring','Spring','Spring','Summer','Summer','Summer','Fall','Fall','Fall','Winter']
        }

# create a DataFrame
df_sales = pd.DataFrame(sales, columns= ['Months', 'Sales','Seasons'])

# print the DataFrame
df_sales

Months  Sales Seasons
0     Jan  22000  Winter
1     Feb  27000  Winter
2     Mar  25000  Spring
3     Apr  29000  Spring
4     May  35000  Spring
5    June  67000  Summer
6    July  78000  Summer
7     Aug  67000  Summer
8     Sep  56000    Fall
9     Oct  56000    Fall
10    Nov  89000    Fall
11    Dec  60000  Winter

The simplest pivot table must have a dataframe and an index . In this case, let us use the 'Months' as our index.

In [ ]:
# create a pivot table where indexes are months
pd.pivot_table(df_sales,index=["Months"])

Sales
Months       
Apr     29000
Aug     67000
Dec     60000
Feb     27000
Jan     22000
July    78000
June    67000
Mar     25000
May     35000
Nov     89000
Oct     56000
Sep     56000

It is possible to create pivot tables over multiple indexes. 

In [ ]:
# to create pivot table having multiple indexes
# index is a list of column names to be considered as indexes
pd.pivot_table(df_sales,index=["Months", "Seasons"])

Sales
Months Seasons       
Apr    Spring   29000
Aug    Summer   67000
Dec    Winter   60000
Feb    Winter   27000
Jan    Winter   22000
July   Summer   78000
June   Summer   67000
Mar    Spring   25000
May    Spring   35000
Nov    Fall     89000
Oct    Fall     56000
Sep    Fall     56000

To create a pivot table for with the index as 'Seasons'. Also, set the values to be 'Sales'.

In [ ]:
# create a pivot table for with the index as 'Seasons' and values as 'Sales'
# index is a list of column names to be considered as indexes
# values represent the numeric data
pd.pivot_table(df_sales,index=["Seasons"],values=["Sales"])

Sales
Seasons              
Fall     67000.000000
Spring   29666.666667
Summer   70666.666667
Winter   36333.333333

The output gives the average sale in each season. The argument `aggfunc` by default will find the average of all values for an index. For example, for the index `Fall`, the average of all the observation having index 'Fall' is given

However, if one is not interested in the average, it is also possible to find the count or the sum of the observations.

Let us find the sum of sales in each season.

In [ ]:
# to create a pivot table for with the index as 'Seasons' and values as 'Sales'
# index is a list of column names to be considered as indexes
# values represent the numeric data
# aggfunc specifies the function 
pd.pivot_table(df_sales,index=["Seasons"],values=["Sales"], aggfunc=np.sum)

Sales
Seasons        
Fall     201000
Spring    89000
Summer   212000
Winter   109000

The `aggfunc` can take a list of functions. 

In [ ]:
# to create a pivot table for with the index as 'Seasons' and values as 'Sales'
# index is a list of column names to be considered as indexes
# values represent the numeric data
# aggfunc specifies the function 
# find the average and count of observations for each season
pd.pivot_table(df_sales,index=["Seasons"],values=["Sales"], aggfunc=[np.mean,len])

mean   len
                Sales Sales
Seasons                    
Fall     67000.000000     3
Spring   29666.666667     3
Summer   70666.666667     3
Winter   36333.333333     3

The output gives the function used above the column name. We see that the mean and count of observations are given.

It is possible to create two-dimensional pivot_tables.

In [ ]:
# create a pivot table for with the index as 'Months', values as 'Sales' and columns as 'Seasons'
# index is a list of column names to be considered as indexes
# values represent the numeric data
# columns is categorical variable(s) whose categories form the columns of the pivot table
# aggfunc specifies the function 
# find the sum observations for each season and month
pd.pivot_table(df_sales, index = ["Months"], values = ["Sales"], columns = ["Seasons"], aggfunc = [np.sum])

sum                           
           Sales                           
Seasons     Fall   Spring   Summer   Winter
Months                                     
Apr          NaN  29000.0      NaN      NaN
Aug          NaN      NaN  67000.0      NaN
Dec          NaN      NaN      NaN  60000.0
Feb          NaN      NaN      NaN  27000.0
Jan          NaN      NaN      NaN  22000.0
July         NaN      NaN  78000.0      NaN
June         NaN      NaN  67000.0      NaN
Mar          NaN  25000.0      NaN      NaN
May          NaN  35000.0      NaN      NaN
Nov      89000.0      NaN      NaN      NaN
Oct      56000.0      NaN      NaN      NaN
Sep      56000.0      NaN      NaN      NaN

The above table is a bit gaudy to look. Let us replace the NaN's with 0's.

In [ ]:
# create a pivot table for with the index as 'Months', values as 'Sales' and columns as 'Seasons'
# index is a list of column names to be considered as indexes
# values represent the numeric data
# columns is categorical variable(s) whose categories form the columns of the pivot table
# aggfunc specifies the function 
# find the sum observations for each season and month
# use fill_value to replace all NaN's as 0's
pd.pivot_table(df_sales, index = ["Months"], values = ["Sales"], columns = ["Seasons"],
               aggfunc = [np.sum], fill_value = 0)

sum                     
         Sales                     
Seasons   Fall Spring Summer Winter
Months                             
Apr          0  29000      0      0
Aug          0      0  67000      0
Dec          0      0      0  60000
Feb          0      0      0  27000
Jan          0      0      0  22000
July         0      0  78000      0
June         0      0  67000      0
Mar          0  25000      0      0
May          0  35000      0      0
Nov      89000      0      0      0
Oct      56000      0      0      0
Sep      56000      0      0      0

The indexes of the pivot table are the months and the columns are the seasons. 

<a id="crosst"> </a>
### 5. Cross Table

Crosstables are similar to pivot tables. They represent the frequency of occurrence of certain groups in the data.

Let us first the read the peoples data.

In [4]:
# read the csv file 
df_people = pd.read_csv('people.csv')

# print head of the data
df_people.head()

Age  Gender Hometown  Height  Qualification Smoker
0   45    Male   Mumbai     167       Graduate    Yes
1   23  Female   Mumbai     170       Graduate     No
2   27    Male   Mumbai     175  Post-graduate     No
3   34    Male    Delhi     155       Graduate     No
4   43  Female   Mumbai     157  Post-graduate    Yes

In [ ]:
# find the count of of qualifications people have from each city
pd.crosstab(df_people.Qualification, df_people.Hometown)

Hometown       Bangalore  Delhi  Mumbai
Qualification                          
Diploma                2      3       1
Graduate               1      2       5
Post-graduate          3      1       3

We see there are more post-graduates from Mumbai and Banglore than in Delhi.

It is possible to rename the column and row names. We use the parameters `rownames` and `columnames` for rows and columns, respectively.

In [ ]:
# find the count of qualifications people have from each city
# rownames are the categories of a variable which form the indexes
# columnames are the categories of a variable which form the indexes
pd.crosstab(df_people.Qualification, df_people.Hometown, rownames = ['Highest Qualification'], colnames=['City'])

City                   Bangalore  Delhi  Mumbai
Highest Qualification                          
Diploma                        2      3       1
Graduate                       1      2       5
Post-graduate                  3      1       3

Lets us now see the average age of smokers based on their city of residence

In [5]:
# find the average age of smokers based on their city of residence
# values represent the numeric data
# aggfunc specifies the function
pd.crosstab(df_people.Hometown, df_people.Smoker, values = df_people.Age, aggfunc = np.mean)

Smoker            No   Yes
Hometown                  
Bangalore  32.333333  52.0
Delhi      34.000000  50.0
Mumbai     39.333333  44.0

The output gives the average age of each of smoker and non-smoker in each city.

<a id="Duplicate"> </a>
### 6. Duplicate

In [ ]:
# create a dictionary
data = { 'Name':['Anne','Bobby','James','Lewis','Ross','Cathrine',
            'Anne','Bobby','Jack','Alisa','Alex','Cathrine'],
    'Company':['Apple','Walmart','Walmart','Intel','Apple','Walmart','Apple',
               'Cognizant','Apple','Apple','Cognizant','Walmart'],
    'Salary':[8500, 6300, 5500, 7400, 3100, 7700, 8500, 6300, 4200, 6200, 8900, 7700]}

# create a DataFrame
df_employee = pd.DataFrame(data, columns=['Name','Company','Salary'])
df_employee

Name    Company  Salary
0       Anne      Apple    8500
1      Bobby    Walmart    6300
2      James    Walmart    5500
3      Lewis      Intel    7400
4       Ross      Apple    3100
5   Cathrine    Walmart    7700
6       Anne      Apple    8500
7      Bobby  Cognizant    6300
8       Jack      Apple    4200
9      Alisa      Apple    6200
10      Alex  Cognizant    8900
11  Cathrine    Walmart    7700

**Duplicate Rows Based on All Columns**

In [ ]:
# Select duplicate rows except first occurrence based on all columns
duplicate_df = df_employee[df_employee.duplicated()]

# print the duplicate rows
print("Duplicate Rows except first occurrence based on all columns are :")
print(duplicate_df)

Duplicate Rows except first occurrence based on all columns are :
        Name  Company  Salary
6       Anne    Apple    8500
11  Cathrine  Walmart    7700


**Duplicate Rows Based on Selected Columns**

Let’s find and select rows based on a single column

In [ ]:
# find and select rows based on the column 'Name'
df_duplicate = df_employee[df_employee.duplicated('Name')]

# print the duplicates
print(df_duplicate)

        Name    Company  Salary
6       Anne      Apple    8500
7      Bobby  Cognizant    6300
11  Cathrine    Walmart    7700


Find and select rows based on two column names.

In [ ]:
# find and select rows based on the columns 'Name' and 'Company'
df_duplicate = df_employee[df_employee.duplicated(['Name', 'Company'])]

# print the duplicates
print(df_duplicate)

        Name  Company  Salary
6       Anne    Apple    8500
11  Cathrine  Walmart    7700


**Drop the Duplicate Rows**

In [ ]:
# drop the duplicates values using drop_duplicates()
df_employee.drop_duplicates()

Name    Company  Salary
0       Anne      Apple    8500
1      Bobby    Walmart    6300
2      James    Walmart    5500
3      Lewis      Intel    7400
4       Ross      Apple    3100
5   Cathrine    Walmart    7700
7      Bobby  Cognizant    6300
8       Jack      Apple    4200
9      Alisa      Apple    6200
10      Alex  Cognizant    8900

<a id="drop"> </a>
### 7. Dropping Rows and Columns

**1. To drop rows** 

We shall use the DataFrame `df`.

In [ ]:
# drop rows using drop()
# index specify the indexes (row names)
df_employee.drop(index = [1,9,5,3,8])

Name    Company  Salary
0       Anne      Apple    8500
2      James    Walmart    5500
4       Ross      Apple    3100
6       Anne      Apple    8500
7      Bobby  Cognizant    6300
10      Alex  Cognizant    8900
11  Cathrine    Walmart    7700

We see that the index numbers specified have been removed. 

Similarly, we can drop columns.

**2. To drop columns** 

We shall use the DataFrame `df` and drop the columns Qualification and Height.

In [ ]:
# drop rows using drop()
# columns specify the column names
df_employee.drop(columns = ['Name', 'Salary'])

Company
0       Apple
1     Walmart
2     Walmart
3       Intel
4       Apple
5     Walmart
6       Apple
7   Cognizant
8       Apple
9       Apple
10  Cognizant
11    Walmart

We see that the two specifies columns have been dropped.

Now let us print the DataFrame df_employee.

In [ ]:
# print the DataFrame df_employee
df_employee

Name    Company  Salary
0       Anne      Apple    8500
1      Bobby    Walmart    6300
2      James    Walmart    5500
3      Lewis      Intel    7400
4       Ross      Apple    3100
5   Cathrine    Walmart    7700
6       Anne      Apple    8500
7      Bobby  Cognizant    6300
8       Jack      Apple    4200
9      Alisa      Apple    6200
10      Alex  Cognizant    8900
11  Cathrine    Walmart    7700

We see the original DataFrame is retained. 

If we wish to make a permanent change in the DataFrame, we use `inplace`.

**Usage of inplace** <br><br>
`inplace` is used when we want to make a permanent to the data. This does not change the data at the source but the data which is read initially.<br>

Let us drop the fourth row from the data and use `inplace` to make a permanent change.

In [ ]:
# drop the fourth row
df_employee.drop(index = [3], inplace = True)

In [ ]:
# print df_employee
df_employee

Name    Company  Salary
0       Anne      Apple    8500
1      Bobby    Walmart    6300
2      James    Walmart    5500
4       Ross      Apple    3100
5   Cathrine    Walmart    7700
6       Anne      Apple    8500
7      Bobby  Cognizant    6300
8       Jack      Apple    4200
9      Alisa      Apple    6200
10      Alex  Cognizant    8900
11  Cathrine    Walmart    7700

It is apparent the fourth row indexed as 3 is dropped. 

<a id="Map"> </a>
### 8. Map and Replace

**`.map()`:**<br>
`.map()` function is used to create a new column by mapping the dataframe column values with the dictionary Key

In [ ]:
# create a DataFrame from a dictionary
df_demography = pd.DataFrame({'Country':['China','India','USA','Indonesia','Brazil'],
                  'Population':[1403500365,1324171354,322179605,261115456,207652865]})

# print the DataFrame
df_demography

Country  Population
0      China  1403500365
1      India  1324171354
2        USA   322179605
3  Indonesia   261115456
4     Brazil   207652865

In [ ]:
# create a dictionary
capital = {
'Germany':'Berlin',
'Brazil':'Brasília',
'Hungary':'Budapest',
'China':'Beijing',
'India':'New Delhi',
'Norway':'Oslo',
'France':'Paris',
'Indonesia': 'Jakarta',
'USA':'Washington'
}

Create a new column - Capital in the DataFrame such that it matches the key-value pair from the country column.

In [ ]:
# create a new column in the DataFrame
df_demography['Capital'] = df_demography['Country'].map(capital)

# print the DataFrame
df_demography

Country  Population     Capital
0      China  1403500365     Beijing
1      India  1324171354   New Delhi
2        USA   322179605  Washington
3  Indonesia   261115456     Jakarta
4     Brazil   207652865    Brasília

**replace():**<br>
It is used to replace any value in the dataframe.

In [ ]:
# print the DataFrame
df_demography

Country  Population     Capital
0      China  1403500365     Beijing
1      India  1324171354   New Delhi
2        USA   322179605  Washington
3  Indonesia   261115456     Jakarta
4     Brazil   207652865    Brasília

In [ ]:
dictionary = {322179605: "NaN", 207652865: "--"}

# values 322179605 and 207652865 are replaced by 'NaN' and '--'
df_demography['Population'].replace(dictionary, inplace = True)

print(df_demography)

     Country  Population     Capital
0      China  1403500365     Beijing
1      India  1324171354   New Delhi
2        USA         NaN  Washington
3  Indonesia   261115456     Jakarta
4     Brazil          --    Brasília


<a id="Groupby"> </a>
### 9. Groupby in Pandas

In [2]:
# create a DataFrame
df_products = pd.DataFrame({ 'Product_ID':[101,102,103,104,105,106],
 'Food_Product':['Cakes','Biscuits','Fruit','Beverages','Cakes','Beverages'],
 'Brand':['Baskin Robbins','Blue Riband','Peach','Horlicks','Mars Muffin','Mirinda'],
 'Sales': [5000, 8000, 7600, 5500, 6500, 9000],
 'Profit': [55000, 67000, 89000, 78000, 55000, 90000] })

# print the DataFrame
print(df_products)

   Product_ID Food_Product           Brand  Sales  Profit
0         101        Cakes  Baskin Robbins   5000   55000
1         102     Biscuits     Blue Riband   8000   67000
2         103        Fruit           Peach   7600   89000
3         104    Beverages        Horlicks   5500   78000
4         105        Cakes     Mars Muffin   6500   55000
5         106    Beverages         Mirinda   9000   90000


**Number of unique values in each column**

In [4]:
df_products_grouped = df_products.groupby("Food_Product")
df_products_grouped 

In [ ]:
type(df_products_grouped)

pandas.core.groupby.generic.DataFrameGroupBy

**Note:** The groupby() applied on a pandas DataFrame returns a `DataFrameGroupBy` object

In [ ]:
# use the nunique() to find the number of unique values in each column
# to_frame converts the data to a DataFrame
df_products.groupby("Food_Product")["Brand"].nunique().to_frame()

Brand
Food_Product       
Beverages         2
Biscuits          1
Cakes             2
Fruit             1

**Sort groupby results**

Turn the groupby object into a regular dataframe by calling `.to_frame()`. It is then possible to re-index with `reset_index()`.

In [ ]:
# use the nunique() to find number of unique values in each column
# to_frame converts the data to a DataFrame
# reset_index resets the index
df_products.groupby('Food_Product')['Sales'].sum().to_frame().reset_index()

Food_Product  Sales
0    Beverages  14500
1     Biscuits   8000
2        Cakes  11500
3        Fruit   7600

Now, you call sort_values() to sort the values of the DataFrame.

In [ ]:
# use the nunique() to find number of unique values in each column
# to_frame converts the data to a DataFrame
# reset_index resets the index
# sort_values sorts the values 
# here by='Sales', implies that the values are sort by this variable
df_products.groupby('Food_Product')['Sales'].sum().to_frame().reset_index().sort_values(by='Sales')

Food_Product  Sales
3        Fruit   7600
1     Biscuits   8000
2        Cakes  11500
0    Beverages  14500